---
# If Jenkins is used, this role is used to enable the permission to access the known_hosts file
- hosts: localhost
  roles:
    - setup_jenkins

# This role is used to check the prompt in OPX or ONIE

- hosts: "{{hostname}}"
  roles:
    - {role: check_opx_onie,tags: 'zero_touch'}

# This role is used to install all the packages after the OPX is installed

- hosts: Leaf1
  become: true
  gather_facts: no
  pre_tasks:
    - name: Update the repo list
      raw: apt-get update
      tags: zero_touch

    - name: Install python
      raw: apt-get -y install python-simplejson
      tags: zero_touch
  roles:
    - {role: pkg_install, tags: 'zero_touch'}

# This role is to upgrade the packages instead of full blown installation

- hosts: cr1_linux
  become: true
  vars_files:
    - roles/pkg_upgrade/vars/main.yml
  roles:
    - {role: pkg_upgrade, tags: ['upgrade', 'smoke_test']}

# This role is to run the smoke test after the switch comes up with the packages installed

- hosts: Leaf2
  become: true
  vars_files:
    - roles/opx_smoke_test/vars/opx_vars.yml
  roles:
    - {role: opx_smoke_test, tags: ['smoke_test', 'zero_touch']}