---
# If Jenkins is used, this role is used to enable the permission to access the known_hosts file
- hosts: localhost
  roles:
    - setup_jenkins

# This role is used to check the prompt in OPX or ONIE

- hosts: "{{onie_hostname}}"
  gather_facts: no
  become: yes
  roles:
    - {role: check_opx_onie,tags: 'zero_touch'}


# This role is to upgrade the packages instead of full blown installation

- hosts: "{{hostname}}"
  become: true
  roles:
    - {role: pkg_upgrade, tags: ['upgrade', 'smoke_test']}




# This role is used to run the smoke test. Pre-task is to check the system status before triggering smoke test

- hosts: "{{hostname}}"
  become: true
  pre_tasks:

    - name: Check the system state running
      shell: opx-show-system-status
      register: system_status_result
      until: "'System State:  running' in system_status_result.stdout"
      retries: 120
      delay: 1
      tags: zero_touch
      ignore_errors: yes

  vars_files:
    - roles/opx_smoke_test/vars/opx_vars.yml
  roles:
    - {role: opx_smoke_test, tags: ['smoke_test', 'zero_touch']}
