---

- block:
  - name: Create LAG {{lagid}}
    command: bash -c "opx-config-lag create --name {{lagid}}"
    register: config_lag
    changed_when: false
    ignore_errors: yes
  - name: Verify the resulted output is success or failure
    assert:
      that: "config_lag.rc == 0"
      msg: "LAG configuration failed"
  - name: Get the lag {{lagid}} from CPS
    command: bash -c "opx-show-lag --name {{lagid}}"
    register: show_cps
    changed_when: false
    ignore_errors: yes
  - name: Verify if the LAG is present in CPS
    assert:
      that: "'No LAG information found' not in show_cps.stdout"
      msg: "LAG is not found in the CPS"
  - name: Get the bond {{lagid}} from the kernel
    command: bash -c "cat /proc/net/bonding/{{lagid}}"
    register: show_kernel
    ignore_errors: yes
  - name: Verify if the LAG is present in the kernel
    assert:
      that: "'No such file or directory' not in show_kernel.stdout"
      msg: "LAG is not found in the kernel"

  when: inventory_hostname in groups['1host']
