---
# vars file for l3_intra_inter

vlanid:   100
interVLAN: 200
unknownMAC:  "00:00:00:11:11:11"
dMAC:    "00:00:00:33:33:33"
staticMAC:    "00:00:00:22:22:22"
IPAddr1:    "100.1.1.1"
IPAddr2:    "100.1.1.3"
IPAddr3:    "100.1.1.2"
interVLANIP1:    "101.1.1.1"
interVLANIP2:    "101.1.1.2"
prefixlen:    "24"
hostprefix:    "32"
bond_interface:    "bond1"
