---
##### Ansible task to send command via OPX's console.
##### (c) 2018 Dell Technologies

- block:

  - name: send command
    delegate_to: localhost
    become: no
    expect:
      command: telnet {{ ansible_console }} {{ console_port }} -e {{ telnet_esc }} 
      timeout: "{{ timeout|default(30) }}"
      responses: "{{ exp | default({}) | combine(default_exp) | combine(extra_exp) }}"
      echo: no
      codec_errors: replace
    register: output
