---
# handlers file for check_opx_onie
- name: wait for switch to come back up
#  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30 timeout=300
#                state=started
  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" delay=10 timeout=300
  become: false

