---

- name: Update all packages to the latest version. THIS TASK MAY TAKE SOME TIME!!!
  apt:
    upgrade: dist 
    update_cache: yes

- name: Reboot the switch for all the OPX Base services to come up
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true

- name: check the switch comes back up
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30 timeout=300
                state=started
  become: false
